apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homie-touch
  namespace: homie

commonLabels:
  app: homie-touch

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
